AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Uploader Lambda Function

Parameters:
  JWTSecretKey:
    Type: String
    Default: 'test-secret-key'
    Description: JWT secret key for token validation
  S3BucketName:
    Type: String
    Default: 'msai-test-bucket'
    Description: S3 bucket name for image storage

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.9

Resources:
  ImageUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          JWT_SECRET_KEY: !Ref JWTSecretKey
          S3_BUCKET_NAME: !Ref S3BucketName
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /upload
            Method: post
        DeleteImage:
          Type: Api
          Properties:
            Path: /upload
            Method: delete

Outputs:
  ImageUploaderApi:
    Description: "API Gateway endpoint URL for Image Uploader function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  ImageUploaderFunction:
    Description: "Image Uploader Lambda Function ARN"
    Value: !GetAtt ImageUploaderFunction.Arn
